In [5]:
import os
print(os.getcwd())

/Users/sudenurgokce/Desktop/SemEval-2027-Task-2-DiCo-NLI/notebooks

In [10]:
import pandas as pd


df = pd.read_csv(
    "../final_data/train/dico_nli_train_track1_participant_labeled.csv"
)

df.head()

,instance_id,pair_id,text1_lang,text2_lang,text1,text2,label
0,dico_phrasis_0000001__en-en__flipped,dico_phrasis_0000001,en,en,Conservative opposition,Conservatives,FORWARD_ENTAILMENT
1,dico_phrasis_0000001__en-en__original,dico_phrasis_0000001,en,en,Conservatives,Conservative opposition,BACKWARD_ENTAILMENT
2,dico_phrasis_0000003__en-en__flipped,dico_phrasis_0000003,en,en,Japanese PM Shinzo Abe,Abe,FORWARD_ENTAILMENT
3,dico_phrasis_0000003__en-en__original,dico_phrasis_0000003,en,en,Abe,Japanese PM Shinzo Abe,BACKWARD_ENTAILMENT
4,dico_phrasis_0000005__en-en__flipped,dico_phrasis_0000005,en,en,ballistic missiles,missiles,FORWARD_ENTAILMENT

In [13]:
print(df.shape)
print(df.columns.tolist())

df["pair_id"].nunique()

(3042, 7)
['instance_id', 'pair_id', 'text1_lang', 'text2_lang', 'text1', 'text2', 'label']

1760

In [14]:
df["pair_id"].value_counts().value_counts().sort_index()

count
1     478
2    1282
Name: count, dtype: int64

In [15]:
df["label"].value_counts()

label
FORWARD_ENTAILMENT     881
BACKWARD_ENTAILMENT    881
EQUIVALENCE            802
NEGATIVE_OTHER         478
Name: count, dtype: int64

In [16]:
pair_sizes= df.groupby("pair_id").size()
single_pair_ids = pair_sizes[pair_sizes==1].index

df[df["pair_id"].isin(single_pair_ids)]["label"].value_counts()

label
NEGATIVE_OTHER    478
Name: count, dtype: int64

In [17]:
df.groupby("label").head(2)[["text1","text2","label"]]

,text1,text2,label
0,Conservative opposition,Conservatives,FORWARD_ENTAILMENT
1,Conservatives,Conservative opposition,BACKWARD_ENTAILMENT
2,Japanese PM Shinzo Abe,Abe,FORWARD_ENTAILMENT
3,Abe,Japanese PM Shinzo Abe,BACKWARD_ENTAILMENT
890,to Philippines,for the Philippine nation,EQUIVALENCE
891,for the Philippine nation,to Philippines,EQUIVALENCE
2564,off Mexico,on Mexico,NEGATIVE_OTHER
2565,abortion bill,against abortion bill,NEGATIVE_OTHER

In [23]:
paired_ids=pair_sizes[pair_sizes==2].index
example_pair_id=paired_ids[4] # number can change to see different results 

df[df["pair_id"]==example_pair_id][["instance_id","text1","text2","label"]]

,instance_id,text1,text2,label
8,dico_phrasis_0000009__en-en__flipped,89 dead,22 Dead,FORWARD_ENTAILMENT
9,dico_phrasis_0000009__en-en__original,22 Dead,89 dead,BACKWARD_ENTAILMENT

In [24]:
dev_df=pd.read_csv("../final_data/dev/dico_nli_dev_track1_participant_labeled.csv")

print(dev_df.shape)
dev_df.head()

(660, 7)

,instance_id,pair_id,text1_lang,text2_lang,text1,text2,label
0,dico_phrasis_0000002__en-en__flipped,dico_phrasis_0000002,en,en,'s war shrine visit,'s shrine visit,FORWARD_ENTAILMENT
1,dico_phrasis_0000002__en-en__original,dico_phrasis_0000002,en,en,'s shrine visit,'s war shrine visit,BACKWARD_ENTAILMENT
2,dico_phrasis_0000004__en-en__flipped,dico_phrasis_0000004,en,en,anti-protest laws,anti-protest law,FORWARD_ENTAILMENT
3,dico_phrasis_0000004__en-en__original,dico_phrasis_0000004,en,en,anti-protest law,anti-protest laws,BACKWARD_ENTAILMENT
4,dico_phrasis_0000008__en-en__flipped,dico_phrasis_0000008,en,en,Iran nuclear experts and also world powers,World powers and Iran,FORWARD_ENTAILMENT

In [25]:
dev_df["label"].value_counts()

label
FORWARD_ENTAILMENT     190
BACKWARD_ENTAILMENT    190
EQUIVALENCE            174
NEGATIVE_OTHER         106
Name: count, dtype: int64