In [1]:
import pandas as pd

train_df= pd.read_csv("../final_data/train/dico_nli_train_track1_participant_labeled.csv")

dev_df=pd.read_csv(  "../final_data/dev/dico_nli_dev_track1_participant_labeled.csv")

print(train_df.shape)
print(dev_df.shape)

(3042, 7)
(660, 7)

In [2]:
dev_df["exact_match"]=(
    dev_df["text1"].str.lower().str.strip() == dev_df["text2"].str.lower().str.strip()
)

dev_df[["text1", "text2", "label", "exact_match"]].head(10)

,text1,text2,label,exact_match
0,'s war shrine visit,'s shrine visit,FORWARD_ENTAILMENT,False
1,'s shrine visit,'s war shrine visit,BACKWARD_ENTAILMENT,False
2,anti-protest laws,anti-protest law,FORWARD_ENTAILMENT,False
3,anti-protest law,anti-protest laws,BACKWARD_ENTAILMENT,False
4,Iran nuclear experts and also world powers,World powers and Iran,FORWARD_ENTAILMENT,False
5,World powers and Iran,Iran nuclear experts and also world powers,BACKWARD_ENTAILMENT,False
6,Nine children,Five children,FORWARD_ENTAILMENT,False
7,Five children,Nine children,BACKWARD_ENTAILMENT,False
8,of all Rage rallies,march of anger,FORWARD_ENTAILMENT,False
9,march of anger,of all Rage rallies,BACKWARD_ENTAILMENT,False

In [3]:
dev_df[dev_df["exact_match"]]["label"].value_counts()

dev_df["exact_match"].value_counts()

exact_match
False    660
Name: count, dtype: int64

In [4]:
dev_df["text2_in_text1"]=dev_df.apply( lambda row: row["text2"].lower().strip() in row["text1"].lower().strip(), axis=1)

dev_df["text1_in_text2"]=dev_df.apply( lambda row: row["text1"].lower().strip() in row["text2"].lower().strip(), axis=1)

print(dev_df["text1_in_text2"].value_counts())
print(dev_df["text2_in_text1"].value_counts())

text1_in_text2
False    597
True      63
Name: count, dtype: int64
text2_in_text1
False    595
True      65
Name: count, dtype: int64

In [5]:
print("text2 in text1")
print(
    dev_df[dev_df["text2_in_text1"]]["label"].value_counts()
)
print("\ntext1 in text2")
print(
    dev_df[dev_df["text1_in_text2"]]["label"].value_counts()
)

text2 in text1
label
FORWARD_ENTAILMENT     55
EQUIVALENCE             5
NEGATIVE_OTHER          3
BACKWARD_ENTAILMENT     2
Name: count, dtype: int64

text1 in text2
label
BACKWARD_ENTAILMENT    55
EQUIVALENCE             5
FORWARD_ENTAILMENT      2
NEGATIVE_OTHER          1
Name: count, dtype: int64

In [7]:
train_df["text2_in_text1"]=train_df.apply( lambda row: row["text2"].lower().strip() in row["text1"].lower().strip(), axis=1)

train_df["text1_in_text2"]=train_df.apply( lambda row: row["text1"].lower().strip() in row["text2"].lower().strip(), axis=1)

print(train_df["text1_in_text2"].value_counts())
print(train_df["text2_in_text1"].value_counts())


print("text2 in text1")
print(
    train_df[train_df["text2_in_text1"]]["label"].value_counts()
)
print("\ntext1 in text2")
print(
    train_df[train_df["text1_in_text2"]]["label"].value_counts()
)

text1_in_text2
False    2768
True      274
Name: count, dtype: int64
text2_in_text1
False    2766
True      276
Name: count, dtype: int64
text2 in text1
label
FORWARD_ENTAILMENT     227
EQUIVALENCE             28
BACKWARD_ENTAILMENT     13
NEGATIVE_OTHER           8
Name: count, dtype: int64

text1 in text2
label
BACKWARD_ENTAILMENT    227
EQUIVALENCE             28
FORWARD_ENTAILMENT      13
NEGATIVE_OTHER           6
Name: count, dtype: int64

In [ ]:
neither=train_df[
    (~train_df["text2_in_text1"] & ~train_df["text1_in_text2"])

]
neither["label"].value_counts()

label
EQUIVALENCE            746
FORWARD_ENTAILMENT     641
BACKWARD_ENTAILMENT    641
NEGATIVE_OTHER         464
Name: count, dtype: int64

In [12]:
def word_subset_features(row):
    text1_words = set(row["text1"].lower().strip().split())
    text2_words = set(row["text2"].lower().strip().split())

    return pd.Series({
        "text2_words_in_text1": text2_words.issubset(text1_words),
        "text1_words_in_text2": text1_words.issubset(text2_words)
    })

In [ ]:
train_df[
    ["text2_words_in_text1", "text1_words_in_text2"]
] = train_df.apply(
    word_subset_features,
    axis=1
)

dev_df[
    ["text2_words_in_text1", "text1_words_in_text2"]
] = dev_df.apply(
    word_subset_features,
    axis=1
)

In [14]:
print("Train - text2 words in text1:")
print(train_df["text2_words_in_text1"].value_counts())

print("\nTrain - text1 words in text2:")
print(train_df["text1_words_in_text2"].value_counts())

print("\nDev - text2 words in text1:")
print(dev_df["text2_words_in_text1"].value_counts())

print("\nDev - text1 words in text2:")
print(dev_df["text1_words_in_text2"].value_counts())

Train - text2 words in text1:
text2_words_in_text1
False    2597
True      445
Name: count, dtype: int64

Train - text1 words in text2:
text1_words_in_text2
False    2594
True      448
Name: count, dtype: int64

Dev - text2 words in text1:
text2_words_in_text1
False    567
True      93
Name: count, dtype: int64

Dev - text1 words in text2:
text1_words_in_text2
False    568
True      92
Name: count, dtype: int64

In [15]:
print("text2 words in text1:")
print(
    train_df[train_df["text2_words_in_text1"]]["label"].value_counts()
)

print("\ntext1 words in text2:")
print(
    train_df[train_df["text1_words_in_text2"]]["label"].value_counts()
)

text2 words in text1:
label
FORWARD_ENTAILMENT     395
EQUIVALENCE             28
BACKWARD_ENTAILMENT     18
NEGATIVE_OTHER           4
Name: count, dtype: int64

text1 words in text2:
label
BACKWARD_ENTAILMENT    395
EQUIVALENCE             28
FORWARD_ENTAILMENT      18
NEGATIVE_OTHER           7
Name: count, dtype: int64

In [16]:
both_true=train_df[
    (train_df["text2_words_in_text1"]) & (train_df["text1_words_in_text2"])
]

print("number of examples:",len(both_true))
print(both_true["label"].value_counts())

both_true[["text1","text2","label"]].head(10)

number of examples: 4
label
EQUIVALENCE    4
Name: count, dtype: int64

,text1,text2,label
958,in Russian psychiatric hospital fire,Fire in Russian psychiatric hospital,EQUIVALENCE
959,Fire in Russian psychiatric hospital,in Russian psychiatric hospital fire,EQUIVALENCE
1104,A brown and white dog,A white and brown dog,EQUIVALENCE
1105,A white and brown dog,A brown and white dog,EQUIVALENCE

In [28]:
def lexical_predict(row):
    text1_words=set(row["text1"].lower().strip().split())
    text2_words=set(row["text2"].lower().strip().split())

    text2_in_text1= text2_words.issubset(text1_words)
    text1_in_text2= text1_words.issubset(text2_words)

    if text2_in_text1 and text1_in_text2:
        return "EQUIVALENCE"
    elif text2_in_text1: 
        return "FORWARD_ENTAILMENT"
    elif text1_in_text2:
        return "BACKWARD_ENTAILMENT"
    else:
        return "EQUIVALENCE"

In [29]:
dev_df["prediction"]=dev_df.apply(lexical_predict, axis=1)

dev_df[["text1","text2","label","prediction"]].head(10)

,text1,text2,label,prediction
0,'s war shrine visit,'s shrine visit,FORWARD_ENTAILMENT,FORWARD_ENTAILMENT
1,'s shrine visit,'s war shrine visit,BACKWARD_ENTAILMENT,BACKWARD_ENTAILMENT
2,anti-protest laws,anti-protest law,FORWARD_ENTAILMENT,EQUIVALENCE
3,anti-protest law,anti-protest laws,BACKWARD_ENTAILMENT,EQUIVALENCE
4,Iran nuclear experts and also world powers,World powers and Iran,FORWARD_ENTAILMENT,FORWARD_ENTAILMENT
5,World powers and Iran,Iran nuclear experts and also world powers,BACKWARD_ENTAILMENT,BACKWARD_ENTAILMENT
6,Nine children,Five children,FORWARD_ENTAILMENT,EQUIVALENCE
7,Five children,Nine children,BACKWARD_ENTAILMENT,EQUIVALENCE
8,of all Rage rallies,march of anger,FORWARD_ENTAILMENT,EQUIVALENCE
9,march of anger,of all Rage rallies,BACKWARD_ENTAILMENT,EQUIVALENCE

In [33]:
lexical_submission=dev_df[["instance_id"]].copy()
lexical_submission["label"]=dev_df["prediction"]

lexical_submission.head()

                             instance_id                label
0   dico_phrasis_0000002__en-en__flipped   FORWARD_ENTAILMENT
1  dico_phrasis_0000002__en-en__original  BACKWARD_ENTAILMENT
2   dico_phrasis_0000004__en-en__flipped          EQUIVALENCE
3  dico_phrasis_0000004__en-en__original          EQUIVALENCE
4   dico_phrasis_0000008__en-en__flipped   FORWARD_ENTAILMENT

In [34]:
lexical_submission.to_csv("../submissions/lexical_baseline_dev.csv", index=False)